package css

import (
	"fmt"
	"testing"
)

type GetNextTokenTestCase struct {
	name     string
	raw      string
	expected []Token
}

// testTokens compares expected token sequence with the sequence generated by lexer
// (skip void and don't care content of End type Token)
func testTokens(expecteds []Token, lexer *Lexer) error {
	i := 0
	for {
		actual := lexer.getNextToken()
		if actual.Type == Void {
			continue
		}
		if i >= len(expecteds) {
			return fmt.Errorf("Generated text exceed expected")
		}

		expected := expecteds[i]

		if expected.Type == End {
			if actual.Type == End {
				return nil
			} else {
				return fmt.Errorf("Expected end sequence, Got: %v", actual)
			}
		}

		if expected != actual {
			return fmt.Errorf("Expected: %v, Got: %v", expected, actual)
		}
		i++
	}
}

func TestGetNextToken(t *testing.T) {
	cases := []GetNextTokenTestCase{
		{
			name: "normal",
			raw: `
body {
  margin: 25px;
  font-size: 14px;
}
h1 {
  color: blue;
  margin-top: 5px;
}`,
			expected: []Token{
				{Type: Selector, Content: "body"},
				{Type: Property, Content: "margin"},
				{Type: Value, Content: "25px"},
				{Type: Property, Content: "font-size"},
				{Type: Value, Content: "14px"},
				{Type: Selector, Content: "h1"},
				{Type: Property, Content: "color"},
				{Type: Value, Content: "blue"},
				{Type: Property, Content: "margin-top"},
				{Type: Value, Content: "5px"},
				{Type: End, Content: ""},
			},
		},
		{
			name: "complex selectors and values",
			raw: `.container, #header > div {
  background: rgba(255, 0, 0, 0.5);
  margin: 10px 20px 30px 40px;
}`,
			expected: []Token{
				{Type: Selector, Content: ".container, #header > div"},
				{Type: Property, Content: "background"},
				{Type: Value, Content: "rgba(255, 0, 0, 0.5)"},
				{Type: Property, Content: "margin"},
				{Type: Value, Content: "10px 20px 30px 40px"},
				{Type: End, Content: ""},
			},
		},
		{
			name: "pseudo-classes and important",
			raw: `a:hover {
  color: red !important;
}
input[type="text"] {
  border: 1px solid #ccc;
}`,
			expected: []Token{
				{Type: Selector, Content: "a:hover"},
				{Type: Property, Content: "color"},
				{Type: Value, Content: "red !important"},
				{Type: Selector, Content: `input[type="text"]`},
				{Type: Property, Content: "border"},
				{Type: Value, Content: "1px solid #ccc"},
				{Type: End, Content: ""},
			},
		},
		{
			name: "no whitespace and empty rule",
			raw:  `.compact{margin:0;padding:0;}.empty{}`,
			expected: []Token{
				{Type: Selector, Content: ".compact"},
				{Type: Property, Content: "margin"},
				{Type: Value, Content: "0"},
				{Type: Property, Content: "padding"},
				{Type: Value, Content: "0"},
				{Type: Selector, Content: ".empty"},
				{Type: End, Content: ""},
			},
		},
	}

	for _, tCase := range cases {
		lexer := newLexer(tCase.raw)
		t.Run(tCase.name, func(t *testing.T) {
			err := testTokens(tCase.expected, lexer)
			if err != nil {
				t.Errorf("%v", err)
			}
		})
	}
}
